add Anchor component to avatar links
blackmann/compa pull request #54
Opened 2024-02-22 10:11 UTC by blackprince001

2024-03-04 14:52 UTC, blackprince001 commented
@blackmann When merging this pull request, you can make clickable filter bars at the top of tagged posts. That means we would have to make a component to take care of clickable components that can be routed with your defined routers.

2024-06-03 05:10 UTC, blackmann requested changes
Good start.

Please address comment and also apply formatting (with biome).

2024-06-03 05:10 UTC, blackmann commented on client/app/components/post-people.tsx
> +							<a href={`/p/${person.username}`}>
We should rather wrap the whole `<li />` content with `<Link />` instead of just the avatar.

2024-06-03 05:10 UTC, blackmann commented on client/app/routes/discussions_.$id.tsx
> +                                <a href={`/p/${post.user.username}`}>
User `<Link />` component instead

2024-06-03 05:10 UTC, blackmann commented on client/app/routes/p.$username.tsx
> +						<a href={`/p/${user.username}`}>
You're adding a link to the profile page on the profile page. No need

2024-06-03 13:24 UTC, closed without merging